spring.application.name=quizmaster

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:quizmaster}
spring.datasource.username=${DB_USER:quizmaster}
spring.datasource.password=${DB_PASS:quizmaster}
spring.datasource.driver-class-name=org.postgresql.Driver

feature.flag=${FEATURE_FLAG:false}
ai.token=${AI_TOKEN:${OPENROUTER_API_KEY:}}
external.api.base-url=${EXTERNAL_API_BASE_URL:}
external.api.key=${EXTERNAL_API_KEY:}
